# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Joachim Wallsin
email: joachim@wallsin.com
description: > # this means to ignore newlines until "baseurl:"
  Webbutvecklare
baseurl: ""
url: "https://wallsin.com" # the base hostname & protocol for your site
facebook: https://www.facebook.com/joachim.wallsin
linkedin: https://se.linkedin.com/in/joachim-wallsin-6b47a810
github: https://github.com/calvinmcgee

# Build settings
markdown: kramdown

gems:
  - jekyll-assets
  - jekyll-sitemap

assets:
  compress:
    css: true
    javascript: true
  prefix: "/assets"
  digest: true
  sources:
    - _assets/sass
    - _assets/js

language: "sv"

menu:
  - title: Hem
    url: "/"
  - title: Om mig
    url: "#om"
  - title: Curriculum vitae
    url: "#cv"
  - title: Portfolio
    url: "#portfolio"

exclude: ["Gemfile", "Gemfile.lock", "wercker.yml", "nbproject"]